### ISSUE TITLE
linking error when building with static boost libraries

### ISSUE THREAD

**Issue by KrisThielemans** [ismrmrd/ismrmrd#114]
I'm investigating if we can use static boost libraries. (Original motivation is [here](https://github.com/gadgetron/gadgetron/issues/711), although this doesn't really apply to ISMRMRD the library doesn't use boost).

This is easy enough:
```sh
cmake -DBoost_USE_STATIC_LIBS=ON ~/sources/ISMRMRD
```
However, there's  a problem with the test. Output of `make VERBOSE=ON`:
```
/usr/bin/c++   -Wall -std=c++11 -O3 -DNDEBUG  -rdynamic CMakeFiles/test_ismrmrd.dir/test_main.cpp.o CMakeFiles/test_ismrmrd.dir/test_acquisitions.cpp.o CMakeFiles/test_ismrmrd.dir/test_images.cpp.o CMakeFiles/test_ismrmrd.dir/test_ndarray.cpp.o CMakeFiles/test_ismrmrd.dir/test_flags.cpp.o CMakeFiles/test_ismrmrd.dir/test_channels.cpp.o CMakeFiles/test_ismrmrd.dir/test_quaternions.cpp.o  -o test_ismrmrd -Wl,-rpath,/home/sirfuser/devel/tmp:/usr/lib/x86_64-linux-gnu/hdf5/serial ../libismrmrd.so.1.4.0 -Wl,-Bstatic -lboost_unit_test_framework -Wl,-Bdynamic /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so -lpthread -lsz -lz -ldl -lm 
CMakeFiles/test_ismrmrd.dir/test_main.cpp.o: In function `main':
test_main.cpp:(.text.startup+0xd): undefined reference to `boost::unit_test::unit_test_main(bool (*)(), int, char**)'
```
There's some stuff on the internet on what you have to do for static links, but I couldn't get my head round it.

PS: tested on Ubuntu 18.04

**Comment by roopchansinghv** [comment]
I have also just run into this same issue with trying to build ISMRMRD for building the most up to date version of GE's converter.  In the latest version of Orchestra, GE has compiled and made available Boost's Unit Test Framework.  So now, when I point ISMRMRD to GE's (static) Boost libraries, it now finds the Unit Test library, and will try to build ISMRMRD's test, but fails on this step.  I am attaching the output of the current attempt to build this. Since it affects the unit tests, and the library itself and accompanying applications compile fine, it's not a show-stopper.  But it would be good to have resolution on this.

[ismrmrd_boost_error.txt]
(https://github.com/ismrmrd/ismrmrd/files/4026204/ismrmrd_boost_error.txt)

**Comment by dchansen** [comment]
Should be fixed in the current master.

**Comment by roopchansinghv** [comment]
Thanks dchansen for taking care of this - I think this is a good change.  However, this is still failing for me.  I am getting another error now, this time about a 'doubly defined main' error, i.e.:

[100%] Linking CXX executable test_ismrmrd
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /usr/local/devGE/Orchestra/3p/lib/libboost_unit_test_framework.a(unit_test_main.o): in function `main':
unit_test_main.cpp:(.text+0x1710): multiple definition of `main'; CMakeFiles/test_ismrmrd.dir/test_main.cpp.o:test_main.cpp:(.text.startup+0x0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/test_ismrmrd.dir/build.make:254: tests/test_ismrmrd] Error 1
make[1]: *** [CMakeFiles/Makefile2:539: tests/CMakeFiles/test_ismrmrd.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

I think that for now, I am going to use the same flag used to indicate statically linking to Boost, to ignore the 'tests' directory, at least till we figure this out, i.e.

diff --git a/CMakeLists.txt b/CMakeLists.txt
index 5e45d49..174f40d 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -235,7 +235,9 @@ endif ()
 
 # TODO: make this work on Windows
 if (NOT WIN32)
-    add_subdirectory(tests)
+   if (NOT Boost_USE_STATIC_LIBS)
+      add_subdirectory(tests)
+   endif ()
 endif ()
 
 # install the matlab api

I am happy to proceed with this patch in my private branch, at least till we have a better handle on what's causing this.

Thank you again!
